Update battle-tooltips.ts
smogon/pokemon-showdown-client pull request #1627
Opened 2020-10-08 00:25 UTC by majorlyps

2020-10-08 00:26 UTC, mia-pi-git commented on src/battle-tooltips.ts
> +                   else {
```suggestion
				  }  else if (pokemon.dynamax) {text += ' Next damage: ' + Math.floor(100 / 8 * Math.min(clientpokemon.statusData.toxicTurns + 1, 15))
                   else {
```

2020-10-08 00:28 UTC, AnnikaCodes requested changes
Can you edit the title of this PR to explain what it does, please?
Also, it's not clear what the `if` statements do — you should work on formatting those better. A newline (and indented block) should follow the `{`.

2020-10-08 00:31 UTC, mia-pi-git commented
> Can you edit the title of this PR to explain what it does, please?
> Also, it's not clear what the `if` statements do — you should work on formatting those better. A newline (and indented block) should follow the `{`.

Adding onto this - see [this](https://github.com/smogon/pokemon-showdown/blob/master/CONTRIBUTING.md) for title guidelines.

2020-10-08 00:32 UTC, AnnikaCodes commented
Also, you should probably implement this by creating an intermediary variable for the damage that Toxic would do rather than using another `if` block. That way, it'll account for the increase in HP from dynamaxing regardless of whether the Pokémon has an ability preventing Toxic damage.

2020-10-08 01:15 UTC, AnnikaCodes commented on src/battle-tooltips.ts
> +				  } else if (pokemon.dynamax) {text += ' Next damage: ' + Math.floor(100 / 8 * Math.min(clientpokemon.statusData.toxicTurns + 1, 15))
```suggestion
					} else if (pokemon.dynamax) {
						text += ' Next damage: ' + Math.floor(100 / 8 * Math.min(clientpokemon.statusData.toxicTurns + 1, 15))
```

2020-10-08 01:17 UTC, AnnikaCodes commented on src/battle-tooltips.ts
>  					if (pokemon.ability === 'Poison Heal' || pokemon.ability === 'Magic Guard') {
```suggestion
					const damageIncreaseStep = pokemon.dynamax ? 100 / 8 : 100 / 16;
					const toxicDamage = Math.floor(damageIncreaseStep * Math.min(clientpokemon.statusData.toxicTurns + 1, 15);
					if (pokemon.ability === 'Poison Heal' || pokemon.ability === 'Magic Guard') {
```

2020-10-08 01:19 UTC, AnnikaCodes commented on src/battle-tooltips.ts
>  					if (pokemon.ability === 'Poison Heal' || pokemon.ability === 'Magic Guard') {
This is what I mean by using another variable (you need to use this in the two remaining if branches for Poison Heal/Magic Guard and regular damage).
```suggestion
					let damageIncreaseStep = 100 / 16;
					if (pokemon.dynamax) damageIncreaseStep /= 2;
					const toxicDamage = Math.floor(damageIncreaseStep * Math.min(clientpokemon.statusData.toxicTurns + 1, 15));
					if (pokemon.ability === 'Poison Heal' || pokemon.ability === 'Magic Guard') {
```

2020-10-08 12:49 UTC, mia-pi-git commented on src/battle-tooltips.ts
> +                   else {
```suggestion
                   else {
```
```suggestion
						text += ' Next damage: ' + Math.floor(100 / 8 * Math.min(clientpokemon.statusData.toxicTurns + 1, 15))
				} else {
```

2020-10-08 13:08 UTC, Marty-D commented
You're actually doubling Toxic damage instead of halving it. If you halve the divisor you make the number bigger, not smaller.

2020-10-26 18:59 UTC, AnnikaCodes commented
@majorlyps are you still working on this?

2020-11-25 00:26 UTC, merged